version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_n8n
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=ecom_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "5680:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=tesis2026
      - N8N_TUNNEL_HTTP_PORT=5678
      - N8N_EDITOR_BASE_URL:=https://unmelodramatically-paragonitic-marcel.ngrok-free.dev 
      - WEBHOOK_URL=https://unmelodramatically-paragonitic-marcel.ngrok-free.dev 
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=ecom_db
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db

volumes:
  db_data:
  n8n_data:
